version: 2
jobs:
  build:
    steps:
      - checkout
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./send-to-s3.sh
            else
              echo "Not the main branch so won't be sent."
